import {
  Briefcase,
  Home,
  Heart,
  BookOpen,
  Target,
  Plane,
  Coffee,
  Star,
  Zap,
  Car,
  Music,
  Camera,
  Gamepad2,
  Dumbbell,
  Utensils,
  type LucideIcon,
  Smile,
  Brush,
  ShoppingCart,
  Keyboard,
} from 'lucide-react';

export const iconOptions = [
  'briefcase',
  'home',
  'heart',
  'book-open',
  'target',
  'shopping-cart',
  'plane',
  'coffee',
  'star',
  'zap',
  'car',
  'music',
  'camera',
  'gamepad-2',
  'dumbbell',
  'utensils',
  'smile',
  'brush',
  'keyboard',
];

export const getIconComponent = (iconName: string): LucideIcon => {
  const iconMap: Record<string, LucideIcon> = {
    briefcase: Briefcase,
    home: Home,
    heart: Heart,
    'book-open': BookOpen,
    target: Target,
    'shopping-cart': ShoppingCart,
    plane: Plane,
    coffee: Coffee,
    star: Star,
    zap: Zap,
    car: Car,
    music: Music,
    camera: Camera,
    'gamepad-2': Gamepad2,
    dumbbell: Dumbbell,
    utensils: Utensils,
    smile: Smile,
    brush: Brush,
    keyboard: Keyboard,
  };

  return iconMap[iconName] || Briefcase;
};
